/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadIdRouteImport } from './routes/read.$id'
import { Route as MangaIdRouteImport } from './routes/manga.$id'
import { Route as ApiPublicMangabuddySplatRouteImport } from './routes/api/public/mangabuddy.$'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdRoute = MangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMangabuddySplatRoute =
  ApiPublicMangabuddySplatRouteImport.update({
    id: '/api/public/mangabuddy/$',
    path: '/api/public/mangabuddy/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/manga/$id': typeof MangaIdRoute
  '/read/$id': typeof ReadIdRoute
  '/api/public/mangabuddy/$': typeof ApiPublicMangabuddySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/manga/$id': typeof MangaIdRoute
  '/read/$id': typeof ReadIdRoute
  '/api/public/mangabuddy/$': typeof ApiPublicMangabuddySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/manga/$id': typeof MangaIdRoute
  '/read/$id': typeof ReadIdRoute
  '/api/public/mangabuddy/$': typeof ApiPublicMangabuddySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/legal'
    | '/library'
    | '/search'
    | '/manga/$id'
    | '/read/$id'
    | '/api/public/mangabuddy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/legal'
    | '/library'
    | '/search'
    | '/manga/$id'
    | '/read/$id'
    | '/api/public/mangabuddy/$'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/legal'
    | '/library'
    | '/search'
    | '/manga/$id'
    | '/read/$id'
    | '/api/public/mangabuddy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  LegalRoute: typeof LegalRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  MangaIdRoute: typeof MangaIdRoute
  ReadIdRoute: typeof ReadIdRoute
  ApiPublicMangabuddySplatRoute: typeof ApiPublicMangabuddySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id': {
      id: '/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof MangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mangabuddy/$': {
      id: '/api/public/mangabuddy/$'
      path: '/api/public/mangabuddy/$'
      fullPath: '/api/public/mangabuddy/$'
      preLoaderRoute: typeof ApiPublicMangabuddySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  LegalRoute: LegalRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  MangaIdRoute: MangaIdRoute,
  ReadIdRoute: ReadIdRoute,
  ApiPublicMangabuddySplatRoute: ApiPublicMangabuddySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
